#Holaaaa
print (3+4)
print (3-4)
print (3*4)
print (3%4)
print (3/4)
print (3**4)
print (3//4)
print ("Mishelle")
print ("Pacheco")
print ("Ecuador")
print ("Estoy disfrutando de 30 días de Python")
print(type(10))
print(type(9.8))
print(type(3.14))
print(type("Asabeneh""Python""Finland"))
print(type("Pacheco"))
print(type("Ecuador"))

